/*
 *
 * Task code generated by SAS Studio 3.4 
 *
 * Generated on '1/20/16, 6:28 PM' 
 * Generated by 'sasdemo' 
 * Generated on server 'BHS-SEB3148.NET.UNLV.EDU' 
 * Generated on SAS platform 'Linux LIN X64 2.6.32-504.23.4.el6.x86_64' 
 * Generated on SAS version '9.04.01M3P06242015' 
 * Generated on browser 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36' 
 * Generated on web client 'http://localhost:10080/SASStudio/34/main?locale=en_US&zone=GMT-08%253A00&http%3A%2F%2Flocalhost%3A10080%2FSASStudio%2F34%2F=' 
 *
 */

title;
footnote;
title1 "List Data for SASHELP.BASEBALL";

/* Sort SASHELP.BASEBALL for BY group processing. */
proc sort data=SASHELP.BASEBALL out=WORK.SORTTEMP;
	by Team;
run;

/* Print the table                            */
proc print data=WORK.SORTTEMP label;
	var Name Team Salary;
	by Team;
run;

quit;
title;
footnote;